In [1]:
#Necessary imports for this code to run smoothly
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import keras
from tensorflow.keras.models import Model
from tensorflow.keras.layers import *
from tensorflow.keras import optimizers
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler

Using TensorFlow backend.

In [6]:
df = pd.read_csv('finalfile.csv')

In [7]:
df

,Customer Name,Refractory,Lining type,campaign,Heat number (life number),Total Heat Time previous (minutes),Total Heat Time (minutes),Scrap (MT),Sponge (MT),Hot Heel (MT),...,Pig iron addition (MT),Scrap (KG),Output (KG),Pig iron (KG),Lumps(%),Pellets(%),Fines(%),Pellets(kg),Lumps(Kg),Fines (Kg)
0,Godavari,SRM,NL,1,7,0.0,175.0,2.5,14.44,NaN,...,NaN,NaN,NaN,NaN,22.0,75.00,3.0,75.0,NaN,NaN
1,Godavari,SRM,NL,1,8,175.0,175.0,2.5,14.44,NaN,...,NaN,NaN,NaN,NaN,22.0,75.00,3.0,75.0,NaN,NaN
2,Godavari,SRM,NL,1,9,175.0,170.0,2.5,14.44,NaN,...,NaN,NaN,NaN,NaN,22.0,75.00,3.0,75.0,NaN,NaN
3,Godavari,SRM,NL,1,10,170.0,215.0,2.5,16.63,NaN,...,NaN,NaN,NaN,NaN,22.0,75.00,3.0,75.0,NaN,NaN
4,Godavari,SRM,NL,1,11,215.0,180.0,2.5,15.45,NaN,...,NaN,NaN,NaN,NaN,22.0,75.00,3.0,75.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1366,HRG,NRM,NL,65,77,160.0,130.0,3.0,5.32,NaN,...,0.50,3000.0,7300.0,500.0,0.0,46.84,NaN,3800.0,NaN,NaN
1367,HRG,NRM,NL,65,78,130.0,150.0,2.8,6.1,NaN,...,0.55,2800.0,7750.0,550.0,0.0,50.07,NaN,4400.0,NaN,NaN
1368,HRG,NRM,NL,65,79,150.0,340.0,3.5,5.21,NaN,...,0.40,3500.0,7700.0,400.0,0.0,43.45,NaN,3800.0,NaN,NaN
1369,HRG,NRM,NL,65,80,340.0,200.0,3.0,6.05,NaN,...,0.50,3000.0,7900.0,500.0,0.0,48.63,NaN,4400.0,NaN,NaN
1370,HRG,NRM,NL,65,81,200.0,160.0,2.8,5.31,NaN,...,0.50,2800.0,7100.0,500.0,0.0,47.14,NaN,3800.0,NaN,NaN

In [8]:
df = df[df['Refractory']=='SRM']
df = df.reset_index(drop=True)

In [9]:
df

,Customer Name,Refractory,Lining type,campaign,Heat number (life number),Total Heat Time previous (minutes),Total Heat Time (minutes),Scrap (MT),Sponge (MT),Hot Heel (MT),...,Pig iron addition (MT),Scrap (KG),Output (KG),Pig iron (KG),Lumps(%),Pellets(%),Fines(%),Pellets(kg),Lumps(Kg),Fines (Kg)
0,Godavari,SRM,NL,1,7,0.0,175.0,2.5,14.44,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
1,Godavari,SRM,NL,1,8,175.0,175.0,2.5,14.44,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
2,Godavari,SRM,NL,1,9,175.0,170.0,2.5,14.44,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
3,Godavari,SRM,NL,1,10,170.0,215.0,2.5,16.63,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
4,Godavari,SRM,NL,1,11,215.0,180.0,2.5,15.45,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,MSP,SRM,NL,63,6,175.0,165.0,0.5,18.3,0.0,...,1.5,0.0,15500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
482,MSP,SRM,NL,63,7,165.0,205.0,0.5,19.52,0.0,...,1.5,0.0,16500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
483,MSP,SRM,NL,63,8,205.0,210.0,0.5,19.52,0.0,...,1.5,0.0,16500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
484,MSP,SRM,NL,63,9,210.0,200.0,0.5,18.88,0.0,...,1.0,0.0,16000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
485,MSP,SRM,NL,63,10,200.0,195.0,1.0,20.45,0.0,...,1.0,0.0,18000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df = df[df['Input energy (KWH)'].notna()]

In [11]:
df

,Customer Name,Refractory,Lining type,campaign,Heat number (life number),Total Heat Time previous (minutes),Total Heat Time (minutes),Scrap (MT),Sponge (MT),Hot Heel (MT),...,Pig iron addition (MT),Scrap (KG),Output (KG),Pig iron (KG),Lumps(%),Pellets(%),Fines(%),Pellets(kg),Lumps(Kg),Fines (Kg)
0,Godavari,SRM,NL,1,7,0.0,175.0,2.5,14.44,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
1,Godavari,SRM,NL,1,8,175.0,175.0,2.5,14.44,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
2,Godavari,SRM,NL,1,9,175.0,170.0,2.5,14.44,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
3,Godavari,SRM,NL,1,10,170.0,215.0,2.5,16.63,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
4,Godavari,SRM,NL,1,11,215.0,180.0,2.5,15.45,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,MSP,SRM,NL,63,6,175.0,165.0,0.5,18.3,0.0,...,1.5,0.0,15500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
482,MSP,SRM,NL,63,7,165.0,205.0,0.5,19.52,0.0,...,1.5,0.0,16500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
483,MSP,SRM,NL,63,8,205.0,210.0,0.5,19.52,0.0,...,1.5,0.0,16500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
484,MSP,SRM,NL,63,9,210.0,200.0,0.5,18.88,0.0,...,1.0,0.0,16000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
485,MSP,SRM,NL,63,10,200.0,195.0,1.0,20.45,0.0,...,1.0,0.0,18000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df = df[df['Input energy previous (KWH)'].notna()]

In [13]:
df

,Customer Name,Refractory,Lining type,campaign,Heat number (life number),Total Heat Time previous (minutes),Total Heat Time (minutes),Scrap (MT),Sponge (MT),Hot Heel (MT),...,Pig iron addition (MT),Scrap (KG),Output (KG),Pig iron (KG),Lumps(%),Pellets(%),Fines(%),Pellets(kg),Lumps(Kg),Fines (Kg)
0,Godavari,SRM,NL,1,7,0.0,175.0,2.5,14.44,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
1,Godavari,SRM,NL,1,8,175.0,175.0,2.5,14.44,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
2,Godavari,SRM,NL,1,9,175.0,170.0,2.5,14.44,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
3,Godavari,SRM,NL,1,10,170.0,215.0,2.5,16.63,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
4,Godavari,SRM,NL,1,11,215.0,180.0,2.5,15.45,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,MSP,SRM,NL,63,6,175.0,165.0,0.5,18.3,0.0,...,1.5,0.0,15500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
482,MSP,SRM,NL,63,7,165.0,205.0,0.5,19.52,0.0,...,1.5,0.0,16500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
483,MSP,SRM,NL,63,8,205.0,210.0,0.5,19.52,0.0,...,1.5,0.0,16500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
484,MSP,SRM,NL,63,9,210.0,200.0,0.5,18.88,0.0,...,1.0,0.0,16000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
485,MSP,SRM,NL,63,10,200.0,195.0,1.0,20.45,0.0,...,1.0,0.0,18000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df = df.reset_index(drop=True)

In [16]:
df = df[df['Output (MT)'].notna()]

In [17]:
df

,Customer Name,Refractory,Lining type,campaign,Heat number (life number),Total Heat Time previous (minutes),Total Heat Time (minutes),Scrap (MT),Sponge (MT),Hot Heel (MT),...,Pig iron addition (MT),Scrap (KG),Output (KG),Pig iron (KG),Lumps(%),Pellets(%),Fines(%),Pellets(kg),Lumps(Kg),Fines (Kg)
0,Godavari,SRM,NL,1,7,0.0,175.0,2.5,14.44,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
1,Godavari,SRM,NL,1,8,175.0,175.0,2.5,14.44,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
2,Godavari,SRM,NL,1,9,175.0,170.0,2.5,14.44,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
3,Godavari,SRM,NL,1,10,170.0,215.0,2.5,16.63,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
4,Godavari,SRM,NL,1,11,215.0,180.0,2.5,15.45,NaN,...,NaN,NaN,NaN,NaN,22.0,75.0,3.0,75.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465,MSP,SRM,NL,63,6,175.0,165.0,0.5,18.3,0.0,...,1.5,0.0,15500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
466,MSP,SRM,NL,63,7,165.0,205.0,0.5,19.52,0.0,...,1.5,0.0,16500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
467,MSP,SRM,NL,63,8,205.0,210.0,0.5,19.52,0.0,...,1.5,0.0,16500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
468,MSP,SRM,NL,63,9,210.0,200.0,0.5,18.88,0.0,...,1.0,0.0,16000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469,MSP,SRM,NL,63,10,200.0,195.0,1.0,20.45,0.0,...,1.0,0.0,18000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
for col in  df.columns[3:]:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [19]:
df = df.fillna(0)

In [20]:
df = df[df['Heat number (life number)']>1]    
df = df.reset_index(drop=True)



#Threshold for total heat time
threshold = 250

for i in range(df.shape[0]):
    if(df.loc[i,'Total Heat Time previous (minutes)']>threshold):
        df.loc[i,'Total Heat Time previous (minutes)']= threshold
    if(df.loc[i,'Total Heat Time (minutes)']>threshold):
        df.loc[i,'Total Heat Time (minutes)']= threshold
        
#Units conversion 
df['Input energy previous (KWH)'] = df['Power previous']*df['Total Heat Time previous (minutes)']/60
df['Input energy (KWH)'] = df['Power']*df['Total Heat Time (minutes)']/60

In [21]:
#Units conversion 
df['Efficiency (MT/KWH)'] = df['Efficiency (MT/KWH)']*1000
df['Previous Output'] = df['Previous Output']*1000
df['Previous Input'] = df['Previous Input']*1000
df['Scrap (MT)'] = df['Scrap (MT)']*1000
df['Sponge (MT)'] = df['Sponge (MT)']*1000
df['Alloys (MT)'] = df['Alloys (MT)']*1000
df['Pig iron addition (MT) '] = df['Pig iron addition (MT) ']*1000

In [25]:
len(np.unique(df['campaign']))

45

In [24]:
df[df['campaign']==50]

,Customer Name,Refractory,Lining type,campaign,Heat number (life number),Total Heat Time previous (minutes),Total Heat Time (minutes),Scrap (MT),Sponge (MT),Hot Heel (MT),...,Pig iron addition (MT),Scrap (KG),Output (KG),Pig iron (KG),Lumps(%),Pellets(%),Fines(%),Pellets(kg),Lumps(Kg),Fines (Kg)
399,21st Century,SRM,NL,50,2,220.0,250.0,5000.0,14760.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
400,21st Century,SRM,NL,50,3,250.0,220.0,6000.0,12410.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
401,21st Century,SRM,NL,50,4,220.0,180.0,5000.0,13330.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
402,21st Century,SRM,NL,50,5,180.0,190.0,5000.0,13140.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
403,21st Century,SRM,NL,50,6,190.0,250.0,4000.0,15280.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
404,21st Century,SRM,NL,50,7,250.0,205.0,5000.0,-6070.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
#40 training campaigns and 5 testing campaigns